services:
  xml-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-server:latest
    container_name: api-server
    ports:
      - "8070:80"
    volumes:
      - /api:/usr/share/nginx/html:ro
    command: >
      sh -c "
      exec nginx -g 'daemon off;'
      "
    restart: unless-stopped